[package]
name = "ua-fm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.12"
rocket = "0.5.0"
serde = "1.0.197"
serde_json = "1.0.114"
tokio = "1.36.0"
